### ISSUE TITLE
4 of your examples can't open with grc and are blank if you try with GNU Radio Companion

### ISSUE THREAD

**Issue by kud3** [bastibl/gr-rds#28]
Can you please fix it, so i can see your flow graphs

**Comment by bastibl** [comment]
Not sure why you are so convinced that the code is broken and not your installation. Anyway, since you provide exactly zero information it's impossible to help. So: How did you install GR. What version. What version of gr-rds did you install. What do you mean with GRC is "blank"? I'd assume that there are any error messages. etc etc

**Comment by kud3** [comment]
It doesn't matter what I asked, i'm sorry. You can delete the question because it has no value.
