### ISSUE TITLE
Updating RDS via TCP Interface

### ISSUE THREAD

**Issue by mrwish7** [bastibl/gr-rds#44]
The example rds_tx GRC file has a TCP Socket PDU interface on port 52001.

Is it possible to update the RDS data (e.g. RT, PS, TA) via this interface with something like netcat. If so, what format is required?

If I netcat some data to port 52001, I can see messages from the running Python script, e.g. -

```
input string: set_ps("NEWRDSPS")
   length: 19\n
not understood
```

So I know that the script is receiving the messages, just not what format they need to be in!

Thanks

**Comment by bastibl** [comment]
Puhh, that's quite some time ago that I implemented it :-) But it's here: https://github.com/bastibl/gr-rds/blob/maint-3.8/lib/encoder_impl.cc#L146-L210

It looks like things like `ta true`, `text abc`, `ps foo` should work. It took quite some time (IIRC ~3 min) until changes took effect, due to relatively large buffers. I think I didn't further optimize it. But the console output of the flowgraph should indicate immediately that the command was parsed and understood.
